---
  # Tasks: Samba4 member server (WIP)
  #
  # Author: Luc Rutten
  # Version: 1.0
  
  - name: "Install dependencies" 
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - acl
      - samba
      - smbclient
      - ntp
      
  - name: "Edit Fstab"
    replace:
      path: /etc/fstab
      regexp: 'errors=remount-ro 0'
      replace: 'user_xattr,acl,barrier=1,errors=remount-ro,relatime 0'
      backup: yes
 
  - name:  "Download template smb.conf.j2 to /etc/samba/smb.conf"
    template:
      src: smb.conf.j2
      dest: /etc/samba/smb.conf
      backup: yes
   
  - name: "Joining domain: {{ smb_realm }}"
    shell: "net ads join -U {{ smb_username }}%{{ smb_password }}"
 
  - name: "Preseed Kerberos version 5"
    raw: "echo krb5-config krb5-config/default_realm string {{ smb_realm }} | sudo debconf-set-selections"
    
  - name: "Install Kerberos"
    apt:
      name: "{{ item }}"
      update_cache: yes
      state: present
    with_items:
      - krb5-user
      - winbind
      - libnss-winbind
 
  - name: "Configure nsswitch for winbind - passwd"
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: 'passwd:         compat'
      line: 'passwd:         compat winbind'
      backup: yes

  - name: "Configure nsswitch for winbind - "
    lineinfile:
      path: /etc/nsswitch.conf
      regexp: 'group:          compat'
      line: 'group:          compat winbind'
      backup: yes
 
#  - name: "Set disk operator permisions for Domain Admins"
#    shell: "net rpc rights grant '{{ smb_workgroup }}\Domain Admins' SeDiskOperatorPrivilege -U{{ smb_username }}%{{ smb_password }}"
