---
  # Handlers: Samba4 member server
  #
  # Author: Luc Rutten
  # Version: 1.0

  - name: "restart_samba_services"
    systemd:
      name: "{{ item }}"
      state: restarted
      enabled: yes
    with_items:
      - smbd
      - nmbd
      - winbind
